# Server port
server.port=${PORT:8080}

# PokéAPI Configuration
pokeapi.base-url=https://pokeapi.co/api/v2
pokeapi.base-url-limit=https://pokeapi.co/api/v2/pokemon

# CORS Configuration
cors.allowed-origins=*

# Proxy Configuration
proxy.base-url=http://localhost:${server.port:8080}

# Logging
logging.level.com.example.pokeproxy=DEBUG
